{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "8.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.2.2.jar",
          "url": "builder-8.2.2.jar",
          "size": 12171594,
          "sha512": "9048cf909686a75556177612a1bad55d80cb863aa6427384d29bfa0aeb7c413496d006aba2f1a579affdaf42584ebe6017a0c64e9cc8237f58992101a2c72ba9",
          "sha256": "904d118e1b1d88992518bc6329bb2f596016641f5b1d97c9bd93f787ab864c21",
          "sha1": "fc78d5edb7ef5ad6012ecd1f96db39ed87180594",
          "md5": "4d392a9f760bce18cf3f59177d4793c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.67"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-8.2.2.jar",
          "url": "builder-8.2.2.jar",
          "size": 12171594,
          "sha512": "9048cf909686a75556177612a1bad55d80cb863aa6427384d29bfa0aeb7c413496d006aba2f1a579affdaf42584ebe6017a0c64e9cc8237f58992101a2c72ba9",
          "sha256": "904d118e1b1d88992518bc6329bb2f596016641f5b1d97c9bd93f787ab864c21",
          "sha1": "fc78d5edb7ef5ad6012ecd1f96db39ed87180594",
          "md5": "4d392a9f760bce18cf3f59177d4793c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.2.2-javadoc.jar",
          "url": "builder-8.2.2-javadoc.jar",
          "size": 400792,
          "sha512": "ef74c79a5c54ba0a5b5c3201841a6a7be4fded95b74102cd35b192d08653720fec310416b95a4b4b6e26643091ec9db51a84e4abfa2fb0c69562fbf5dfd2af88",
          "sha256": "04ed33475e64ea8f36406e6c020e6d03abecbe58c0500df3a10f2cc710049721",
          "sha1": "d5ea64aba4f81db6f55bf347e6f5b5a51525a211",
          "md5": "3a037b25d781c9511202f27a6765593a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-8.2.2-sources.jar",
          "url": "builder-8.2.2-sources.jar",
          "size": 281987,
          "sha512": "352f3e074f5a375bf54630dc1cde890d3b417dae6938ea2fef1a5729fa8de19419d2afe16751e1367ec9c607f08ed9f61b7893be24ec955591dd6b4b1cd35e8d",
          "sha256": "3231056f6bc44aa8156bad1d0d30f2272c0e95d37d2cbcef0cdca2b28579f731",
          "sha1": "59fcb73c81f369c318bda30a8cce90ecb0105a35",
          "md5": "68ed2ed33f41fc1ec7b2bbd8ca42ce52"
        }
      ]
    }
  ]
}
