{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "8.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.2.2.jar",
          "url": "gradle-api-8.2.2.jar",
          "size": 312619,
          "sha512": "46527e6636867d35cbe8b3c17cfbff2527088b46e67d01a9a00cfecf1eb8dc9383a10c0a9bdab991ec10e0323b6109f11b5574ed3e8689d5b39c2750bbf84b5e",
          "sha256": "15d1fb5e892d0bf03f371271cf67bae95db8e89082d12a8b58165d49f4288643",
          "sha1": "ff8f3ca6cca706ab812699276be6c64a6a9dd28d",
          "md5": "5c40c5185c62b3494f9fbc453bf2eb90"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "8.2.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-8.2.2.jar",
          "url": "gradle-api-8.2.2.jar",
          "size": 312619,
          "sha512": "46527e6636867d35cbe8b3c17cfbff2527088b46e67d01a9a00cfecf1eb8dc9383a10c0a9bdab991ec10e0323b6109f11b5574ed3e8689d5b39c2750bbf84b5e",
          "sha256": "15d1fb5e892d0bf03f371271cf67bae95db8e89082d12a8b58165d49f4288643",
          "sha1": "ff8f3ca6cca706ab812699276be6c64a6a9dd28d",
          "md5": "5c40c5185c62b3494f9fbc453bf2eb90"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.2.2-javadoc.jar",
          "url": "gradle-api-8.2.2-javadoc.jar",
          "size": 151062,
          "sha512": "5da43c41499d4e62d459e7b2f568afffad34453cb7026b83162939e56eac8582784f497140f6c7ef42d3d829167e3e167b8f2e9ebb7775824ee0df3ed9138120",
          "sha256": "571a351f7c39ad981bdc875fdcd8350620f78f2937e9403b2c74f168cbc8d0e8",
          "sha1": "606461669e7aac068cfc01ccd3519bf86f1d7bc7",
          "md5": "d3ccf71e3cd98cfb40a4ddfd28a90ae7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-8.2.2-sources.jar",
          "url": "gradle-api-8.2.2-sources.jar",
          "size": 307234,
          "sha512": "e3779fd17861706643c4191683731615074069d81573c62de6c777162a826fc3f149c893b0d210477334fc47b011e1c6e81bdde12c98b526e2e8b98abe52b7d3",
          "sha256": "539a7ad744853244475bc64d5b65ba1dc7e732b0a7c6484160c1eac87858f310",
          "sha1": "85f7c00ddc7f0d868352f2c601d01363a8be8fd8",
          "md5": "9277c3ba9ae170926590bcdc65ba4cf5"
        }
      ]
    }
  ]
}
