{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder-model",
    "version": "8.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "builder-model-8.2.2.jar",
          "url": "builder-model-8.2.2.jar",
          "size": 119017,
          "sha512": "50470d47d8715fcf32f89cca4c83180a5bca31654624edc49a4d31f7b8d0b511e3c64c3a5d8e4b72f50db4f27c19d498acba3f8a9c7d98704dda729a7644d19c",
          "sha256": "4a10c9f4ed6fbb576339f8ca7c77867923c7566ef5a2b122f43f3586e5964b4e",
          "sha1": "2335b64f5856414571f74898885d8ad86a6bcb3b",
          "md5": "99262433f790ca47c80fe06c8541e0d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "annotations",
          "version": {
            "requires": "31.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-model-8.2.2.jar",
          "url": "builder-model-8.2.2.jar",
          "size": 119017,
          "sha512": "50470d47d8715fcf32f89cca4c83180a5bca31654624edc49a4d31f7b8d0b511e3c64c3a5d8e4b72f50db4f27c19d498acba3f8a9c7d98704dda729a7644d19c",
          "sha256": "4a10c9f4ed6fbb576339f8ca7c77867923c7566ef5a2b122f43f3586e5964b4e",
          "sha1": "2335b64f5856414571f74898885d8ad86a6bcb3b",
          "md5": "99262433f790ca47c80fe06c8541e0d0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.2.2-javadoc.jar",
          "url": "builder-model-8.2.2-javadoc.jar",
          "size": 291069,
          "sha512": "b9a1d7e64ecad17063e09ce69a40c3176836feddee5f8af679cdb577e7822830429bc8f242c774fb5a5fe3fd5307571407ed58ea575825013de6d2ca1f9c7244",
          "sha256": "be3be41fb85c9d8fd783686fab9cde50a1218e4a4a1b450c14c4fc350b21237b",
          "sha1": "0ba785d6fe0233877ac24f834fff6cc2c095aaaf",
          "md5": "097f54e71105f6c51acbf916431423da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-model-8.2.2-sources.jar",
          "url": "builder-model-8.2.2-sources.jar",
          "size": 142820,
          "sha512": "ea1acfc3baf610584dde2d78ece3769d0678195ded46a93a60db5ffa70822467005efa6cc3a20293261540748c9516d3596b02365e13f64814881e037ed19179",
          "sha256": "4ca64b8bdb11feba007d4c9c2938592f0278a9ae76bfd6b93446cff01cba0c9f",
          "sha1": "b8b7e94eff2e5d71f6685f57977877bbe5d0749d",
          "md5": "bcc19ac1d4afda29d890d7749bf876dd"
        }
      ]
    }
  ]
}
